name: 'Publish Blog Post'
description: 'Publish a blog post to the hosting supported (Dev.to)'
author: 'Thiago Mendonca'
branding:
  icon: 'book-open'
  color: 'purple'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
  devToApiKey:
    description: API Key to use to publish blog post to Dev.to website
    required: false    
  publishTo:
    description: Websites to publish blog post
    required: true
    default: 'dev.to,medium.com'
  includeFolders:
    description: Folders to look for post files to publish/update. Multiple folders can be speficied, one folder per line
    required: false
  commitMessage:
    description: 'Commit message template to be used when a published file is commited with update data. %file is replaced with the file name and %lang with language'
    required: false
    default: 'publish/update %file with updated data'
runs:
  using: 'node20'
  main: 'dist/index.js'
