name: Test Markdown Reviewer and Translator

permissions:
  contents: write
  
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-blog-post:
    runs-on: ubuntu-latest
    name: A test job to run the Publish Blog Post action
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test the publish-blog-post action
        uses: ./ # Uses an action in the root directory
        id: publish-blog-post
        with:
          devToApiKey: ${{ secrets.DEV_TO_API_KEY }}
          includeFolders: |-
            pages/posts
